// Het Nederlands.
//
// De sleutel is de Engelse zin zoals hij in de broncode staat, niet een naam
// als `settings.timer.inspection`. Dat betekent dat een zin die hier nog niet
// staat gewoon in het Engels doorkomt in plaats van als een lege sleutel op het
// scherm te belanden -- de juiste manier om onvolledig te zijn.
//
// {naam} tussen accolades is een gat dat de app invult. Die namen moeten aan
// beide kanten hetzelfde zijn.

export const NL = {
  " before {date}": " voor {date}",
  " from {date}": " van {date}",
  " · best {n}": " · beste {n}",
  " · the cross could have gone in {n} moves": " · kruis kon in {n} zetten",
  " · your own": " · van jezelf",
  " — {n} of them new to this device": " — daarvan {n} nieuw voor dit toestel",
  "\"{name}\" deleted.": "\"{name}\" verwijderd.",
  "\"{name}\" saved — {n} cases.": "\"{name}\" bewaard — {n} gevallen.",
  "+  Put a set together yourself": "+  Zelf een reeks samenstellen",
  "+ time": "+ tijd",
  "+{time} on your ao5": "+{time} op je ao5",
  ", best {time}": ", beste {time}",
  ", which a browser never sends to a server. So nothing is uploaded and nothing is kept — it simply works for whoever you send it to.": ", dat een browser nooit naar een server stuurt. Er wordt dus niets geüpload en niets bewaard — hij werkt gewoon bij wie je hem naartoe stuurt.",
  ", {n} are already here": ", {n} staan er al",
  ", {n} line skipped": ", {n} regel overgeslagen",
  ", {n} lines skipped": ", {n} regels overgeslagen",
  ", {n} new {word}": ", {n} nieuwe {word}",
  "0 selected": "0 gekozen",
  "12.34 or 1:23.45": "12.34 of 1:23.45",
  "3 or more shorter": "3 of meer korter",
  "A case you had never drilled": "Een geval dat je nog nooit gedaan had",
  "A day counts from {goal} on. ": "Een dag telt mee vanaf {goal}. ",
  "A session of twenty in a row": "Een sessie van twintig achter elkaar",
  "A solve before seven in the morning.": "Een solve voor zeven uur ’s ochtends.",
  "A solve between midnight and five in the morning.": "Een solve tussen middernacht en vijf uur.",
  "A solve under {time}": "Een solve onder {time}",
  "A tick at a steady tempo, to teach you to keep your turning even. It runs on while you solve.": "Een tik op een vast tempo, om je draaisnelheid gelijkmatig te leren houden. Loopt door terwijl je solvet.",
  "A year of days": "Een jaar aan dagen",
  "Add": "Toevoegen",
  "add": "toevoegen",
  "Add a time": "Tijd toevoegen",
  "Add a time by hand": "Tijd met de hand toevoegen",
  "Add it": "Erbij zetten",
  "Alg sheet": "Algblad",
  "all": "alles",
  "all cases": "alle gevallen",
  "All six in one day": "Alle zes op één dag",
  "All the statistics": "Alle statistieken",
  "All your times": "Al je tijden",
  "Already done today": "Al gedaan vandaag",
  "An ao5 under {time}": "Een ao5 onder {time}",
  "An ordinary start; never counts as a touch": "Gewone start; telt nooit als een tik",
  "and": "en",
  "And {n} times before that.": "En daarvoor nog {n} keer.",
  "are all recognised; if a scramble follows it, that comes along too.": "worden allemaal herkend; staat er een scramble achter, dan gaat die mee.",
  "as csv": "als csv",
  "as fast as you dare": "zo snel als je durft",
  "As many solves as you can inside the time. The clock runs on between them.": "Zoveel mogelijk solves binnen de tijd. De klok loopt door tussen je solves.",
  "as slowly as you can without stopping": "zo langzaam mogelijk zonder te stoppen",
  "as text": "als tekst",
  "At this rate you get there around {date} — after your date. That is no disaster, it is only honest.": "Op dit tempo haal je het rond {date} — na je datum. Dat is geen ramp, het is alleen eerlijk.",
  "At this rate you get there around {date}. Put a date beside it and it will say whether that is in time.": "Op dit tempo haal je het rond {date}. Zet er een datum bij en hij zegt of dat op tijd is.",
  "At this rate you will not get there — your times are not coming down at the moment. That need not mean anything bad, but the app cannot put a date on it.": "Op dit tempo kom je er niet — je tijden zakken op het moment niet. Dat hoeft niets ergs te betekenen, maar een datum kan de app er niet op plakken.",
  "Average": "Gemiddelde",
  "Average per stage ({n} solves)": "Gemiddeld per deel ({n} solves)",
  "Average {time}. These times are not yours and are not kept.": "Gemiddelde {time}. Deze tijden zijn niet van jou en worden niet bewaard.",
  "Awkward cross": "Lastig kruis",
  "Back to plain": "Terug naar gewoon",
  "Best": "Beste",
  "best": "beste",
  "Best and worst": "Beste en slechtste",
  "Best ao5": "Beste ao5",
  "Best ao5 #{n}": "Beste ao5 #{n}",
  "best day {date} — {time}": "beste dag {date} — {time}",
  "Best ever": "Beste ooit",
  "best of this session": "beste van deze sessie",
  "Best of {name}": "Beste van {name}",
  "best {label}": "beste {label}",
  "Between you it stands {a}–{b}.": "Onderling staat het {a}–{b}.",
  "Big display": "Groot scherm",
  "Blue mat": "Blauw matje",
  "Both in the slot · corner twisted": "Allebei in de sleuf · hoek gedraaid",
  "Both in the slot · corner twisted and edge flipped": "Allebei in de sleuf · hoek gedraaid en rand omgekeerd",
  "Both in the slot · edge flipped": "Allebei in de sleuf · rand omgekeerd",
  "Bowtie": "Strik",
  "By when": "Voor wanneer",
  "Cabinet — {got} of {all}": "Kast — {got} van {all}",
  "Cancels inspection, closes a selection, leaves the big display": "Inspectie afbreken, selectie sluiten, grote weergave uit",
  "Card saved.": "Kaartje bewaard.",
  "Case book": "Gevallenboek",
  "Cases refused:": "Gevallen afgekeurd:",
  "Celebrate records": "Record vieren",
  "Challenges": "Uitdagingen",
  "Chance manages this": "Toeval haalt dit",
  "Check it": "Nakijken",
  "Check whether there are times on the timer": "Kijk of er tijden op de timer staan",
  "Checked on a real cube and added — {n} moves.": "Nagekeken op een echte kubus en toegevoegd — {n} zetten.",
  "Choose a file": "Bestand kiezen",
  "Choose a session": "Kies sessie",
  "Choose where it should go.": "Kies waar hij heen moet.",
  "clear": "wissen",
  "Clear every time in this session?": "Alle tijden van deze sessie wissen?",
  "Clear the times": "Tijden wissen",
  "Click to copy": "Klik om te kopiëren",
  "Close": "Sluiten",
  "Close the session": "Sessie afsluiten",
  "Colours": "Kleuren",
  "Compare with": "Vergelijk met",
  "Competition hall": "Wedstrijdzaal",
  "Competition round": "Wedstrijdronde",
  "Confetti and celebrating records": "Confetti en records vieren",
  "Connect timer": "Verbind timer",
  "Connected to {name}.": "Verbonden met {name}.",
  "Connecting did not work. Is the timer on, and is it not already connected to another app or phone?{detail}": "Verbinden lukte niet. Staat de timer aan, en is hij niet al verbonden met een andere app of telefoon?{detail}",
  "Connecting failed. Turn the timer off and on again, and disconnect it from other devices or apps. [{raw}]": "Verbinden mislukt. Zet de timer even uit en weer aan, en koppel hem los van andere apparaten of apps. [{raw}]",
  "Connecting…": "Verbinden…",
  "Copy": "Kopieer",
  "Copy as text": "Kopieer als tekst",
  "Copy link": "Link kopiëren",
  "Copying did not work in this browser.": "Kopiëren lukte niet in deze browser.",
  "Coral": "Koraal",
  "Corner in the slot, edge on top": "Hoek in de sleuf, rand boven",
  "Corner in the slot, edge on top · corner twisted": "Hoek in de sleuf, rand boven · hoek gedraaid",
  "Corner on top, edge in the slot": "Hoek boven, rand in de sleuf",
  "Corner on top, edge in the slot · edge flipped": "Hoek boven, rand in de sleuf · rand omgekeerd",
  "Count the time up afterwards": "Tijd laten oplopen",
  "Counts again.": "Telt weer mee.",
  "Create and move": "Aanmaken en verplaatsen",
  "Cross could have gone in": "Kruis kon in",
  "Cross round over — {n} solves": "Kruis-ronde voorbij — {n} solves",
  "Cross tip": "Cross-tip",
  "Cross tip after your solve": "Cross-tip na je solve",
  "Cross · Antisune": "Kruis · Antisune",
  "Cross · bowtie": "Kruis · strik",
  "Cross · C shape": "Kruis · C-vorm",
  "Cross · double Sune": "Kruis · dubbele Sune",
  "Cross · H": "Kruis · H",
  "Cross · headlights": "Kruis · koplampen",
  "Cross · Pi": "Kruis · Pi",
  "Cross · Sune": "Kruis · Sune",
  "Cross · T": "Kruis · T",
  "Cross · T shape": "Kruis · T-vorm",
  "Cube": "Kubus",
  "Daily goal": "Dagdoel",
  "Daily scramble done": "Dagscramble gedaan",
  "dark": "donker",
  "day": "dag",
  "Days": "Dagen",
  "days": "dagen",
  "Decimals": "Decimalen",
  "Delete": "Verwijderen",
  "delete": "wis",
  "Delete \"{name}\" with every time in it?": "\"{name}\" verwijderen met alle tijden erin?",
  "delete the last time — touch once to confirm": "laatste tijd wissen — tik 1× om te bevestigen",
  "Delete this time?": "Deze tijd verwijderen?",
  "Delete {n} times?": "{n} tijden verwijderen?",
  "Delete? Tap <strong>once</strong> to confirm": "Wissen? Tik <strong>1×</strong> om te bevestigen",
  "Details": "Details",
  "Details of that solve": "Details van die solve",
  "Disconnect": "Loskoppelen",
  "Do the daily scramble": "Doe de dagscramble",
  "does not count": "telt niet mee",
  "Does not count towards your averages.": "Telt niet mee in je gemiddelden.",
  "Doesn't count": "Telt niet mee",
  "doesn't count": "telt niet",
  "Done": "Gedaan",
  "done": "klaar",
  "Dot": "Punt",
  "Dot · all loose": "Punt · alles los",
  "Dot · anti shield": "Punt · anti-schild",
  "Dot · double bend": "Punt · dubbele bocht",
  "Dot · free standing": "Punt · vrijstaand",
  "Dot · little cross": "Punt · kruisje",
  "Dot · mouse": "Punt · muis",
  "Dot · rucksack": "Punt · rugzak",
  "Dot · shield": "Punt · schild",
  "Dot · with headlights": "Punt · met koplampen",
  "Double Sune": "Dubbele Sune",
  "Drill cases": "Gevallen trainen",
  "Drill this case now": "Dit geval nu oefenen",
  "Drill your weakest {group}": "Oefen je zwakste {group}",
  "Drilling": "Trainen",
  "Due for a repeat — {when}.": "Aan herhaling toe — {when}.",
  "due now": "nu aan de beurt",
  "e.g. 15 or 14.5": "bv. 15 of 14.5",
  "e.g. pop, OLL skip": "bv. pop, OLL skip",
  "e.g. right hand, x rotation at the end": "bv. rechterhand, x-rotatie op het einde",
  "Early bird": "Vroege vogel",
  "Every move of cross costs you": "Elke zet kruis kost je",
  "Every puzzle at least once, inside the same day.": "Elke puzzel minstens één keer, binnen dezelfde dag.",
  "Every step ticked off. From here it is only mileage.": "Alle stappen afgevinkt. Vanaf hier is het alleen nog kilometers maken.",
  "Everything": "Alles",
  "everything in it is already here.": "alles wat erin staat heb je hier al.",
  "Everything mixed together": "Alles door elkaar",
  "everything mixed together": "alles door elkaar",
  "Everything replaced: {n}.": "Alles vervangen: {n}.",
  "Everything together": "Alles bij elkaar",
  "Everything your timer reports ({n} slots).": "Alles wat je timer doorgeeft ({n} plekken).",
  "Export": "Exporteren",
  "Export times": "Tijden exporteren",
  "Fair enough. The wheel forgets nothing.": "Ook goed. Het rad vergeet niets.",
  "Fastest": "Snelste",
  "Feedback": "Reactie",
  "File saved. Put it on your other device and open it there.": "Bestand bewaard. Zet het op je andere toestel en open het daar.",
  "First 50": "Eerste 50",
  "first time": "eerste tijd",
  "First what you have not had yet, then at random. {n} cases.": "Eerst wat je nog niet gehad hebt, daarna willekeurig. {n} gevallen.",
  "Fish · headlights at the back": "Vis · koplampen achter",
  "Fish · headlights at the front": "Vis · koplampen voor",
  "Five in a row under {time}": "Vijf op rij onder {time}",
  "Five minutes": "Vijf minuten",
  "Five solves, best and worst dropped. A result at the end.": "Vijf solves, beste en slechtste eraf. Aan het eind een resultaat.",
  "For a solve you did somewhere else. It goes at the end of the session that is open now.": "Voor een solve die je ergens anders gedaan hebt. Hij komt achteraan in de sessie die nu open staat.",
  "for cstimer": "voor cstimer",
  "for example: the seventeen I do not know yet": "bijvoorbeeld: de zeventien die ik nog niet ken",
  "For you, {what} inspection is fastest. That is not advice from a book — it is in your own times.": "Bij jou is {what} inspectie het snelst. Dat is geen advies uit een boek — het staat in je eigen tijden.",
  "Fresh — up again {when}.": "Vers — weer aan de beurt {when}.",
  "From a file": "Uit een bestand",
  "From another device": "Van een ander toestel",
  "From the next scramble on.": "Vanaf de volgende scramble.",
  "from the timer": "van de timer",
  "from the timer memory": "uit timergeheugen",
  "From {name}": "Van {name}",
  "Full. The next card is here on Monday.": "Vol. De volgende kaart staat er maandag.",
  "Games and modes": "Spelletjes en modi",
  "Gave up": "Opgegeven",
  "Gets it ready; letting go starts the time": "Klaarzetten; loslaten start de tijd",
  "Hands on and straight off again": "Handen erop en er meteen af",
  "Have you really got better?": "Ben je echt beter geworden?",
  "Headlights": "Koplampen",
  "Hide the time while you solve": "Tijd verbergen tijdens je solve",
  "Hold": "Vasthouden",
  "Hold and let go to start": "Vasthouden en loslaten om te starten",
  "Hold time": "Vasthoudtijd",
  "Hold to start": "Vasthouden om te starten",
  "Holding, and too slow": "Vasthouden en te traag",
  "Hook": "Haakje",
  "How many in a row under your threshold? One over and you start again.": "Hoeveel achter elkaar onder je drempel? Eén erover en je begint opnieuw.",
  "How many solves": "Aantal solves",
  "How the wheel treats you": "Hoe het rad met je omgaat",
  "How your record came down": "Hoe je record gezakt is",
  "I can do this": "Dit kan ik",
  "I cannot read that as a time. Try 12.34 or 1:23.45.": "Dat lees ik niet als een tijd. Probeer 12.34 of 1:23.45.",
  "I will do it": "Ik doe het",
  "Ice blue": "IJsblauw",
  "In the list of times": "In de lijst met tijden",
  "in {n} day": "over {n} dag",
  "in {n} days": "over {n} dagen",
  "Inspection": "Inspectie",
  "inspection": "inspectie",
  "Into the bin": "Naar de vuilbak",
  "Is your timer not in the list? This button shows everything nearby, without filtering on the name.": "Staat je timer niet in de lijst? Deze knop laat alles zien wat in de buurt is, zonder te filteren op naam.",
  "it breaks the cross or another slot": "breekt het kruis of een andere sleuf",
  "it breaks the first two layers": "breekt de eerste twee lagen",
  "it changes nothing": "verandert niets",
  "it does not solve this case": "lost dit geval niet op",
  "it leaves pieces the wrong way up": "laat stukken verkeerd om liggen",
  "it leaves the whole cube turned": "draait de hele kubus",
  "it moves corners as well": "verzet ook hoeken",
  "it moves edges as well": "verzet ook randen",
  "it moves only one kind": "verzet er maar één soort",
  "it solves a different case": "lost een ander geval op",
  "it turns nothing over": "draait niets om",
  "Keep a streak of days": "Dagen op rij bijhouden",
  "Keep the screen awake": "Scherm wakker houden",
  "Keeping and settings": "Bewaren en instellen",
  "Kept": "Bewaard",
  "Kept.": "Bewaard.",
  "Keys and gestures": "Toetsen en gebaren",
  "Knee · back": "Knie · achter",
  "Knee · front": "Knie · voor",
  "Knee · left": "Knie · links",
  "Knee · right": "Knie · rechts",
  "Language": "Taal",
  "Last 50": "Laatste 50",
  "Last ao5": "Laatste ao5",
  "Last attempt failed — {text} [{name}{extra}]": "Laatste poging mislukt — {text} [{name}{extra}]",
  "last {n}": "laatste {n}",
  "Lay the cross and stop. Afterwards you see in how many moves it could have gone — the one exercise the app can mark for you.": "Leg alleen het kruis en stop. Achteraf zie je in hoeveel zetten het had gekund — de enige oefening waarbij de app je kan nakijken.",
  "Learn to solve": "Leer oplossen",
  "Learning an algorithm is not a slope but a step: one day you no longer have to think. These are the days that happened on.": "Een algoritme leren is geen helling maar een trede: op een dag hoef je niet meer na te denken. Dit zijn de dagen waarop dat gebeurde.",
  "Least known at the top — {done} of {all} drilled": "Slechtst gekend bovenaan — {done} van {all} geoefend",
  "light": "licht",
  "Line": "Streep",
  "Line · beam left": "Streep · balk links",
  "Line · beam right": "Streep · balk rechts",
  "Line · bench": "Streep · bank",
  "Line · bridge": "Streep · brug",
  "Line · crane": "Streep · kraan",
  "Line · eagle": "Streep · adelaar",
  "Line · fish": "Streep · vis",
  "Line · fish head": "Streep · vissenkop",
  "Line · glasses left": "Streep · bril links",
  "Line · glasses right": "Streep · bril rechts",
  "Line · guard": "Streep · bewaker",
  "Line · hole": "Streep · gat",
  "Line · key": "Streep · sleutel",
  "Line · kite left": "Streep · vlieger links",
  "Line · kite right": "Streep · vlieger rechts",
  "Line · monkey": "Streep · aap",
  "Line · P left": "Streep · P links",
  "Line · P right": "Streep · P rechts",
  "Line · plank left": "Streep · plank links",
  "Line · plank right": "Streep · plank rechts",
  "Line · stealth": "Streep · stealth",
  "Line · tall stairs": "Streep · hoge trap",
  "Line · wall": "Streep · muur",
  "Line · worm": "Streep · worm",
  "long": "lang",
  "longest": "langste",
  "Longest cross": "Langste kruis",
  "Longest streak": "Langste reeks",
  "Look": "Uiterlijk",
  "Look and feel": "Sfeer",
  "Looking back": "Terugblik",
  "Loop · left": "Lus · links",
  "Loop · right": "Lus · rechts",
  "Making the cross": "Kruis maken",
  "manage": "beheer",
  "Marathon": "Marathon",
  "Marathon of {n}": "Marathon van {n}",
  "Marathon under {n}s — {streak} in a row{bar}": "Marathon onder {n}s — {streak} op rij{bar}",
  "Mark the best and the worst": "Beste en slechtste markeren",
  "Measure cross, F2L, OLL and PLL separately": "Cross, F2L, OLL en PLL apart meten",
  "Merge": "Samenvoegen",
  "Metronome": "Metronoom",
  "Minutes": "Minuten",
  "minutes": "minuten",
  "Mode": "Modus",
  "More than your usual day ({n}).": "Meer dan je gewone dag ({n}).",
  "most so far: {n}": "hoogste tot nu: {n}",
  "Move": "Verplaatsen",
  "move": "verplaats",
  "my slowest ten": "mijn traagste tien",
  "Name": "Naam",
  "Name of a cube": "Naam van een kubus",
  "Name of the set": "Naam van de reeks",
  "Name of this session": "Naam van deze sessie",
  "Never played each other yet.": "Nog nooit tegen elkaar gespeeld.",
  "never yet": "nog nooit",
  "new scramble": "nieuwe scramble",
  "New scramble.": "Nieuwe scramble.",
  "New session": "Nieuwe sessie",
  "New session started.": "Nieuwe sessie gestart.",
  "New set": "Nieuwe reeks",
  "New set — {group}": "Nieuwe reeks — {group}",
  "New time found": "Nieuwe tijd gevonden",
  "New times found": "Nieuwe tijden gevonden",
  "Next case": "Volgend geval",
  "Night owl": "Nachtbraker",
  "no date": "zonder datum",
  "No day with solves in it yet.": "Nog geen dag met solves erin.",
  "No details to ask for.": "Geen details op te vragen.",
  "no error object": "geen foutobject",
  "No longer kept.": "Niet meer bewaard.",
  "no name": "geen naam",
  "No new times on your timer.": "Geen nieuwe tijden op je timer.",
  "no penalty": "geen straf",
  "No permission for bluetooth. Allow it in your browser and try again{detail}": "Geen toestemming voor bluetooth. Sta het toe in je browser en probeer opnieuw{detail}",
  "No time to delete.": "Geen tijd om te wissen.",
  "No timer chosen. Was the list empty? Turn the timer on and disconnect it from other apps or phones.": "Geen timer gekozen. Stond er niets in de lijst? Zet de timer aan en koppel hem los van andere apps of telefoons.",
  "No timer connected yet.": "Nog geen timer verbonden.",
  "No times on this device yet.": "Nog geen tijden op dit toestel.",
  "No times recognised in what is there.": "Geen tijden herkend in wat er staat.",
  "No times to copy yet.": "Nog geen tijden om te kopiëren.",
  "No times to save yet.": "Nog geen tijden om te bewaren.",
  "No times yet.": "Nog geen tijden.",
  "no usable algorithm": "geen bruikbaar algoritme",
  "No, never mind": "Nee, laat maar",
  "none": "niets",
  "normal": "normaal",
  "Not kept with this time.": "Niet bewaard bij deze tijd.",
  "not started yet": "nog niet begonnen",
  "not yet": "nog niet",
  "Not yet after all": "Toch nog niet",
  "Note": "Notitie",
  "Noted. Spin again if you dare.": "Genoteerd. Draai nog eens als je durft.",
  "nothing at the moment": "niets op dit moment",
  "Nothing but DNFs. That counts as a session too.": "Alleen DNFs. Dat telt ook als een sessie.",
  "Nothing chosen. Turn a group on, or pick a wider selection.": "Niets gekozen. Zet een groep aan, of kies een ruimere selectie.",
  "Nothing due — everything is still fresh.": "Niets aan de beurt — alles is nog vers.",
  "Nothing due — everything you have drilled is still fresh. Come back tomorrow.": "Niets aan de beurt — alles wat je geoefend hebt is nog vers. Kom morgen terug.",
  "Nothing found with this filter.": "Niets gevonden met deze filter.",
  "nothing measurable": "niets meetbaars",
  "Nothing to close yet. Do a few solves first.": "Nog niets om af te sluiten. Doe eerst een paar solves.",
  "Nothing to go over — everything you have drilled is still fresh.": "Niets te herhalen — alles wat je geoefend hebt is nog vers.",
  "Nothing to share yet.": "Nog niets om te delen.",
  "Nothing to show with this choice.": "Niets om te laten zien met deze keuze.",
  "nothing yet today": "nog niets vandaag",
  "nothing — only this session": "niets — alleen deze sessie",
  "Now": "Nu",
  "Of the cases you have drilled, {slow} is your slowest ({slowTime}) and {fast} your fastest ({fastTime}).": "Van de gevallen die je geoefend hebt is {slow} je traagste ({slowTime}), en {fast} je snelste ({fastTime}).",
  "Off this device": "Van dit toestel af",
  "Official random-state scramble · click to copy": "Officiële random-state scramble · klik om te kopiëren",
  "On an iPhone that is under Settings → the browser → Bluetooth, on a Mac under ": "Op iPhone staat dat bij Instellingen → de browser → Bluetooth, op een Mac onder ",
  "on the display": "op het display",
  "On this day": "Op deze dag",
  "On your mat": "Op je matje",
  "Once: inspection. Twice quickly: delete the last time": "Eén keer: inspectie. Twee keer snel: laatste tijd wissen",
  "One file with all your sessions, times, scrambles and preferences.\n      Save it here, open it there.": "Eén bestand met al je sessies, tijden, scrambles en voorkeuren.\n      Bewaar het hier, open het daar.",
  "One scramble, one try, the same for everybody. Compare with a friend.": "Eén scramble, één poging, voor iedereen dezelfde. Vergelijk gerust met een vriend.",
  "One short touch": "1× kort aanraken",
  "One time per line.": "Een tijd per regel.",
  "Only for {name}; every session has its own target.": "Alleen voor {name}; elke sessie heeft zijn eigen doel.",
  "Only scrambles with a cross of 5 moves or fewer.": "Alleen scrambles met een kruis van 5 zetten of korter.",
  "Only scrambles with a cross of 7 moves or more.": "Alleen scrambles met een kruis van 7 zetten of langer.",
  "only what I chose myself": "alleen wat ik zelf koos",
  "only what I have drilled": "alleen wat ik geoefend heb",
  "Or to a new session": "Of naar een nieuwe sessie",
  "Over {n} scrambles another colour was on average {moves} moves shorter. That is what being colour neutral would save you.": "Over {n} scrambles was een andere kleur gemiddeld {moves} zetten korter. Dat is wat kleurneutraal zijn je zou schelen.",
  "Over {n} solves there is no link in your times between the length of the cross and how long you took. So there is nothing to correct — your average is what it is.": "Over {n} solves is er in jouw tijden geen verband te zien tussen de lengte van het kruis en hoe lang je erover deed. Er valt dus ook niets te corrigeren — je gemiddelde is wat het is.",
  "Over {n} solves you got an average set of scrambles. Your average is what it is.": "Over {n} solves kreeg je een doorsnee set scrambles. Je gemiddelde is wat het is.",
  "Pair on top": "Paar boven",
  "Paper": "Papier",
  "Paste times": "Tijden plakken",
  "Penalise, move or delete several at once": "Meerdere tegelijk straffen, verplaatsen of wissen",
  "Per cube": "Per kubus",
  "Pick the file you saved on your other device.": "Kies het bestand dat je op je andere toestel bewaard hebt.",
  "Pick the file you saved on your other device. An export from csTimer works here too.": "Kies het bestand dat je op je andere toestel bewaard hebt. Een export uit csTimer werkt hier ook.",
  "Picture": "Voorbeeld",
  "Picture of the scramble": "Voorbeeld van de scramble",
  "Plain": "Gewoon",
  "plain": "strak",
  "Play": "Spelen",
  "Play a game to the end": "Een spelletje uitspelen",
  "Practice": "Oefenen",
  "Practice streak": "Oefenreeks",
  "Practise": "Oefenen",
  "Practise the cross only": "Alleen het kruis oefenen",
  "Press <kbd>space</kbd>": "Tik <kbd>spatie</kbd>",
  "Print": "Afdrukken",
  "Progress": "Vooruitgang",
  "Pull the lever. Three reels, one task, and not one of the 2640 outcomes is one you would set yourself.": "Trek aan de hendel. Drie rollen, één opdracht, en geen van de 2640 uitkomsten is er een die je jezelf zou geven.",
  "Putting the last layer round, everything already the right way up. 21 cases.": "De laatste laag rondzetten, alles ligt al goed gedraaid. 21 gevallen.",
  "Puzzle": "Puzzel",
  "Puzzle for the new session": "Puzzel voor de nieuwe sessie",
  "Quick actions: +2, DNF, ★, does not count, move, delete": "Snelacties: +2, DNF, ★, telt niet, verplaatsen, wissen",
  "Quick cross": "Vlot kruis",
  "Reached. Set a new aim under it and this keeps meaning something.": "Gehaald. Zet er een nieuw doel onder, dan blijft dit iets zeggen.",
  "Ready to start": "Klaar om te starten",
  "Recognition": "Herkennen",
  "Records": "Records",
  "Records and looking back": "Records en terugblik",
  "Refused — it leaves the cube turned. Put the counter-rotation after it (y, x2, …) and the picture will match too.": "Afgekeurd — hij laat de kubus gedraaid achter. Zet er de tegendraai achter (y, x2, …), dan klopt het plaatje ook.",
  "Refused — {why}. Tried on a real cube, so it is not the app.": "Afgekeurd — {why}. Op een echte kubus geprobeerd, dus het ligt niet aan de app.",
  "Replace everything": "Alles vervangen",
  "Reset button on the timer": "Resetknop op de timer",
  "Ring and accents": "Ring en accenten",
  "Ring colours along with your pace": "Ring kleurt mee met je tempo",
  "Ring lives along": "Ring leeft mee",
  "Round": "Ronde",
  "round": "rond",
  "Round finished": "Ronde afgelopen",
  "Round — solve {at} of {all}": "Ronde — solve {at} van {all}",
  "Save": "Bewaren",
  "Save as a card": "Bewaar als kaart",
  "Save file": "Bewaar bestand",
  "Save the card": "Kaartje bewaren",
  "Scramble": "Scramble",
  "Scramble (may be empty)": "Scramble (mag leeg)",
  "Scramble copied.": "Scramble gekopieerd.",
  "Scramble of the day": "Scramble van de dag",
  "Scramble of the day — one try": "Scramble van de dag — één poging",
  "Scramble of the day — you get one try.": "Scramble van de dag — je hebt één poging.",
  "Scrambles to taste": "Scrambles op maat",
  "search": "zoek",
  "Search and filter": "Zoeken en filteren",
  "Search scrambles, notes and times": "Zoek in scramble, notitie of tijd",
  "seconds": "seconden",
  "select": "selecteer",
  "Sending did not work; just save the card instead.": "Versturen lukte niet; bewaar het kaartje dan gewoon.",
  "Sending did not work; just save the file instead.": "Versturen lukte niet; bewaar het bestand dan gewoon.",
  "Send…": "Versturen…",
  "Session": "Sessie",
  "session": "sessie",
  "Session {n}": "Sessie {n}",
  "Sessions": "Sessies",
  "sessions": "sessies",
  "Set — {name}": "Reeks — {name}",
  "Settings": "Instellingen",
  "Share": "Delen",
  "Share your ao5": "Deel je ao5",
  "short": "kort",
  "Short and done. Five solves is a session too.": "Kort en klaar. Ook vijf solves is een sessie.",
  "Short touch: once for inspection · twice to delete the last time · hold to start": "Kort aanraken: 1× inspectie · 2× de laatste tijd wissen · vasthouden om te starten",
  "Short touch: twice to delete the last time · hold to start": "Kort aanraken: 2× de laatste tijd wissen · vasthouden om te starten",
  "show all": "alles tonen",
  "Show every bluetooth device": "Toon alle bluetooth-apparaten",
  "Simply what the scrambler gives.": "Gewoon wat de scrambler geeft.",
  "Since {date}, over all your sessions together.": "Sinds {date}, over al je sessies samen.",
  "small": "klein",
  "Small bump · left": "Kleine hobbel · links",
  "Small bump · right": "Kleine hobbel · rechts",
  "So do not count the first few solves of a session when you judge yourself.": "Reken de eerste paar solves van een sessie dus niet mee als je jezelf beoordeelt.",
  "So you are better off stopping earlier than you think.": "Je stopt dus beter vroeger dan je denkt.",
  "solve": "solve",
  "Solve until you stop. Everything in sight.": "Solve tot je stopt. Alles zichtbaar.",
  "Solves": "Solves",
  "solves": "solves",
  "solves ever": "solves ooit",
  "solves in {n} day": "solves in {n} dag",
  "solves in {n} days": "solves in {n} dagen",
  "Somebody sent you this": "Iemand stuurde je dit",
  "Somebody solved in another window; this list has been brought up to date.": "Er is in een ander venster gesolved; deze lijst is nu bijgewerkt.",
  "Sound": "Geluid",
  "Spin": "Draaien",
  "Spin again": "Nog eens draaien",
  "Splits": "Splits",
  "Square · left": "Vierkant · links",
  "Square · long left": "Vierkant · lang links",
  "Square · long right": "Vierkant · lang rechts",
  "Square · right": "Vierkant · rechts",
  "Stand-in scramble: the official scrambler could not load · click to copy": "Reservescramble: de officiële scrambler kon niet laden · klik om te kopiëren",
  "Standard": "Standaard",
  "Start": "Beginnen",
  "start": "starten",
  "Start a duel": "Duel beginnen",
  "Started at": "Begonnen om",
  "Starts the inspection, when it is on": "Start de inspectie, als die aanstaat",
  "Statistics": "Statistieken",
  "Still to go": "Nog te gaan",
  "Stop": "Stoppen",
  "stop selecting": "stop selectie",
  "Stops a running time": "Stopt een lopende tijd",
  "streak": "reeks",
  "Surprise": "Verrassing",
  "Surprise me": "Verras me",
  "Surprise mode — {n} to go.": "Verrassingsmodus — nog {n} te gaan.",
  "Surprise over — {n} solves": "Verrassing voorbij — {n} solves",
  "Surprise — {n} to go, you see them all afterwards": "Verrassing — nog {n} te gaan, je ziet ze straks allemaal",
  "Swiping left": "Naar links vegen",
  "Swiping right": "Naar rechts vegen",
  "System Settings → Privacy → Bluetooth, on Windows under Settings → Privacy.": "Systeeminstellingen → Privacy → Bluetooth, op Windows bij Instellingen → Privacy.",
  "Taken on. The counter is running.": "Aangenomen. De teller loopt.",
  "Tap": "Tik",
  "Tap the time for its scramble.": "Tik de tijd aan voor de scramble.",
  "Tapping the screen": "Tikken op het scherm",
  "Target time": "Doeltijd",
  "Target time with a date": "Doeltijd met een datum",
  "Task done. The rule is between you and you.": "Opdracht gehaald. De regel weet jij zelf.",
  "Tempo": "Tempo",
  "text": "tekst",
  "That file could not be read.": "Dat bestand kon niet gelezen worden.",
  "that goes through GAN’s own app, over a protocol that is not public.": "dat loopt via GAN’s eigen app over een protocol dat niet openbaar is.",
  "That is it for now": "Tot hier",
  "That is it for now — {name}": "Tot hier — {name}",
  "That is {gap} — more about outliers than about pace, when it is large.": "Dat scheelt {gap} — meer aan uitschieters dan aan tempo, als dat groot is.",
  "That many days running with at least one solve.": "Zoveel dagen achter elkaar minstens één solve.",
  "That many minutes of solving in a day keeps the flame alight": "Zoveel minuten solven op een dag houdt de vlam brandend",
  "That many solves in a day keeps the flame alight": "Zoveel solves op een dag houdt de vlam brandend",
  "That one is already there.": "Die staat er al.",
  "The app follows, but never interrupts a running solve": "De app volgt, maar onderbreekt nooit een lopende solve",
  "The browser is blocking this connection. Is the page served over https?{detail}": "De browser blokkeert deze verbinding. Werkt de pagina wel via https?{detail}",
  "The cases could not be loaded.": "De gevallen konden niet geladen worden.",
  "The colour you solve on": "Kleur waarop je solvet",
  "the corner ends up somewhere else": "de hoek belandt elders",
  "The counter": "De teller",
  "The cross could have gone in {n} moves on {colour} — on {other} in {m}.": "Het kruis kon in {n} zetten op {colour} — op {other} in {m}.",
  "The cross could have gone in {n} moves, and no shorter on any colour.": "Het kruis kon in {n} zetten, en op geen enkele kleur korter.",
  "The cross could have gone in {n} moves.": "Cross kon in {n} zetten.",
  "The cross could have gone in {n} on {colour}, but in {m} on {other}.": "Cross kon in {n} op {colour}, maar in {m} op {other}.",
  "The cross only": "Alleen het kruis",
  "The cross only — {n} to go": "Alleen het kruis — nog {n} te gaan",
  "the edge ends up somewhere else": "de rand belandt elders",
  "the first five": "de eerste vijf",
  "The first one": "De eerste",
  "The first step of OLL in two looks: the yellow cross.": "De eerste stap van OLL in twee kijkbeurten: het gele kruis.",
  "The five that hurt": "De vijf die pijn deden",
  "The last layer made yellow in one go. All 57 cases.": "De laatste laag in één keer geel maken. Alle 57 gevallen.",
  "The link carries your times in the part after the": "De link draagt je tijden in het stuk achter de",
  "The next one is the same scramble.": "De volgende is dezelfde scramble.",
  "The other one": "De ander",
  "The pair in the front right slot. All 41 cases.": "Het paar in de sleuf rechtsvoor. Alle 41 gevallen.",
  "the pair is already home": "het paar staat al goed",
  "The same as space, on a phone": "Hetzelfde als spatie, op een telefoon",
  "the same one again": "nog eens dezelfde",
  "The same scramble until you are under {time} — try {n}": "Dezelfde scramble tot je onder {time} zit — poging {n}",
  "The scramble of the day, the same one for everybody.": "De scramble van de dag, die voor iedereen dezelfde is.",
  "The second step of OLL in two looks, with the cross already made.": "De tweede stap van OLL in twee kijkbeurten, met het kruis al gemaakt.",
  "The shape of your session": "De vorm van je sessie",
  "The sheet is on your clipboard.": "Het blad staat op je klembord.",
  "The time during a solve": "Tijd tijdens solve",
  "The time is your solves added up, not how long the app was open.": "De tijd is je solves bij elkaar opgeteld, niet hoe lang de app openstond.",
  "The timer dropped out during your solve — the time is now running on the app’s own clock. Press space or tap to stop.": "Timer losgekoppeld tijdens je solve — de tijd loopt nu op de klok van de app. Druk op spatie of tik om te stoppen.",
  "The timer’s lights cannot be driven from here: ": "De lampjes van de timer zijn hier niet mee te sturen: ",
  "The wheel": "Het rad",
  "The {n} cases you are slowest on, and nothing else.": "De {n} gevallen waar je het traagst op bent, en niets anders.",
  "Theme": "Thema",
  "There are no times in this file.": "Er staan geen tijden in dit bestand.",
  "There is little to win here: on your colour you are as good as always already on the shortest.": "Er valt hier weinig te winnen: op jouw kleur zit je zo goed als altijd al op de kortste.",
  "These times are not yours and are not kept.": "Deze tijden zijn niet van jou en worden niet bewaard.",
  "These {n} times": "Deze {n} tijden",
  "This browser cannot talk to bluetooth. On a computer or Android, Chrome or Edge works; on an iPhone, a browser like Bluefy.": "Deze browser kan niet met bluetooth praten. Op de computer of Android werkt Chrome of Edge, op iPhone een browser als Bluefy.",
  "This browser cannot talk to the timer{detail}": "Deze browser kan niet met de timer praten{detail}",
  "This browser keeps nothing (private mode?). Settings last until you reload.": "Deze browser bewaart niets (privémodus?). Instellingen gelden tot je herlaadt.",
  "This browser keeps nothing (private mode?). Your times stay until you reload the page.": "Deze browser bewaart niets (privémodus?). Je tijden blijven staan tot je de pagina herlaadt.",
  "This device": "Dit apparaat",
  "This device has no bluetooth, or the browser is not allowed near it. ": "Dit apparaat heeft geen bluetooth, of de browser mag er niet bij. ",
  "This file comes from a newer version of the app. Update it first.": "Dit bestand komt uit een nieuwere versie van de app. Werk deze eerst bij.",
  "This file does not come from Cubetimer or csTimer.": "Dit bestand komt niet uit Cubetimer of csTimer.",
  "This is a whole file with sessions in it. Use \"to another device\" — that keeps your sessions, scrambles and notes intact.": "Dit is een heel bestand met sessies erin. Gebruik \"naar een ander toestel\" — daar blijven je sessies, scrambles en notities heel.",
  "This is not a readable cubetimer file.": "Dit is geen leesbaar cubetimer-bestand.",
  "This is the one I use": "Dit is de mijne",
  "This is your only session. Make one below.": "Dit is je enige sessie. Maak er hieronder een aan.",
  "This scramble keeps coming back until you are under your usual pace on it": "Deze scramble blijft komen tot je er onder je gewone tempo op zit",
  "This scramble stays until you are under {time}.": "Deze scramble blijft staan tot je onder {time} zit.",
  "This starts a new run; the last one does not carry on.": "Dit begint een nieuwe reeks; de vorige telt niet verder.",
  "This time": "Deze tijd",
  "This week — {name}": "Deze week — {name}",
  "This window will not open in this browser.": "Dit venster gaat niet open in deze browser.",
  "Those times were already there.": "Die tijden stonden er al.",
  "three times running, the same scramble": "drie keer achter elkaar, dezelfde scramble",
  "Threshold": "Drempel",
  "Throw away everything on this device and replace it with the file? {n} times disappear.": "Alles op dit toestel weggooien en vervangen door het bestand? {n} tijden verdwijnen.",
  "Ticks per minute": "Tikken per minuut",
  "Time": "Tijd",
  "time": "tijd",
  "Time added.": "Tijd toegevoegd.",
  "Time deleted.": "Tijd verwijderd.",
  "Time is up — {n} {word}": "Vijf minuten voorbij — {n} {word}",
  "Time on the cube": "Tijd aan de kubus",
  "Times": "Tijden",
  "times": "tijden",
  "Times for {id} cleared.": "Tijden van {id} gewist.",
  "Times — {name}": "Tijden — {name}",
  "To another device": "Naar een ander toestel",
  "Today": "Vandaag",
  "today": "vandaag",
  "today at {time}": "vandaag om {time}",
  "Today: {time}. A new one tomorrow.": "Vandaag: {time}. Morgen weer een nieuwe.",
  "Together these five cost you {time} in averages. Their scrambles are here, so you can set them up again.": "Samen kostten deze vijf je {time} aan gemiddelden. Ze staan er met hun scramble bij, zodat je ze opnieuw kunt leggen.",
  "Too early to say. Chance alone manages this difference in {n} cases out of a hundred, so this is just as likely a good evening as progress.": "Nog niet te zeggen. Toeval alleen haalt dit verschil in {n} van de honderd gevallen, dus dit is even goed een goede avond als vooruitgang.",
  "Too few cases in this group to choose from.": "Te weinig gevallen in deze groep om uit te kiezen.",
  "Too few times to look back on. Do a few and come back.": "Nog te weinig tijden om iets terug te kijken. Solve er een paar en kom terug.",
  "Too few times yet to know what is good enough.": "Nog te weinig tijden om te weten wat goed genoeg is.",
  "Too few times yet to say whether you are on schedule.": "Nog te weinig tijden om te zeggen of je op schema ligt.",
  "Too little measured yet — do {n} more first, then it knows which they are.": "Nog te weinig gemeten — doe er eerst {n} meer, dan weet hij welke dat zijn.",
  "Tools": "Gereedschap",
  "total": "totaal",
  "Touch for inspection · hold to start": "Aanraken voor inspectie · vasthouden om te starten",
  "Turn on": "Aanzetten",
  "Turn the setup on a solved cube and the case is in front of you. {n} case(s) were refused while loading and are not offered.": "Draai de opzet op een opgeloste kubus; dan staat het geval voor je. {n} geval(len) werden bij het inladen afgekeurd en niet aangeboden.",
  "Turn the setup on a solved cube, then solve only that case. Your times stay with the case and do not go into your session.": "Draai de opzet op een opgeloste kubus, en solve dan alleen dat geval. Je tijden blijven bij het geval en komen niet in je sessie.",
  "Turning": "Aan het draaien",
  "turning": "aan het draaien",
  "Turning the corners": "Hoeken draaien",
  "Twenty in a row without a DNF": "Twintig op rij zonder DNF",
  "Two names, taking turns on the same device. Best of five.": "Twee namen, om de beurt solven op hetzelfde toestel. Best of vijf.",
  "Two of you": "Met zijn tweeën",
  "Two short touches": "2× kort aanraken",
  "Typeface of the digits": "Lettertype van de cijfers",
  "Unexpected data from the timer.": "Onverwachte data van de timer.",
  "unknown group": "onbekende groep",
  "Until it lands": "Tot hij zit",
  "Until next time": "Tot de volgende",
  "Vibration": "Trillen",
  "Warm-up off. From now on everything counts again.": "Opwarmen uit. Vanaf nu telt alles weer mee.",
  "Warming up": "Opwarmen",
  "Warming up — these do not count": "Opwarmen — deze tellen niet mee",
  "Warming up — these do not count. Turn it off when you start.": "Opwarmen — deze tellen niet mee. Zet het uit als je begint.",
  "Ways through it — the star is yours": "Manieren — de ster is die van jou",
  "Weak spots": "Zwaktes",
  "Web Bluetooth is not available in this browser": "Web Bluetooth is niet beschikbaar in deze browser",
  "Web Bluetooth is not available in this browser.": "Web Bluetooth is niet beschikbaar in deze browser.",
  "what I haven't done yet": "wat ik nog niet gedaan heb",
  "what I need to refresh": "wat ik moet opfrissen",
  "What if": "Wat als",
  "What takes you longest": "Waar je het langst over doet",
  "When it clicked": "Toen het klikte",
  "Where you lose it": "Waar je het verliest",
  "Which case are you looking at? Tap the name.": "Welk geval zie je? Tik de naam aan.",
  "While you are warming up your solves do not count towards your averages — your first few are measurably slower and they need not muddy your figures.": "Tijdens het opwarmen tellen je solves niet mee in je gemiddelden — je eerste paar zijn meetbaar trager en die hoeven je cijfers niet te vertroebelen.",
  "Will be added as {time}.": "Wordt toegevoegd als {time}.",
  "with one hand": "met één hand",
  "with the cube on your knee": "met de kubus op je knie",
  "with your eyes shut after the inspection": "met je ogen dicht na de inspectie",
  "without looking at the time": "zonder naar de tijd te kijken",
  "without turning your wrist": "zonder je pols te draaien",
  "Without {what} your average would be {then} instead of {now}.": "Zonder {what} was je gemiddelde {then} in plaats van {now}.",
  "worst": "slechtste",
  "Yes. This difference is too big to be chance — chance manages it only {n} times in a hundred.": "Ja. Dit verschil is te groot om toeval te zijn — toeval haalt het maar {n} keer op de honderd.",
  "yesterday": "gisteren",
  "You are as quick at the start as at the end. That is rare, and it saves you warming up.": "Je bent even snel aan het begin als aan het eind. Dat is zeldzaam en het scheelt je opwarmtijd.",
  "You are done here when: {what}": "Je bent hier klaar als: {what}",
  "You are on schedule: at this rate you are there around {date}.": "Je ligt op schema: op dit tempo zit je er rond {date}.",
  "You are quickest at {quick}, and {n}% slower at {slow}.": "Je bent op je snelst bij {quick}, en {n}% trager bij {slow}.",
  "You did this scramble on {when} in {then} — {gap} faster now.": "Deze scramble deed je op {when} in {then} — {gap} sneller nu.",
  "You did this scramble on {when} in {then} — {gap} slower now.": "Deze scramble deed je op {when} in {then} — {gap} trager nu.",
  "You gain per week": "Je wint per week",
  "You got {gap} faster during this session. That is exactly what you sat down for.": "Je bent tijdens deze sessie {gap} sneller geworden. Dat is precies waarvoor je ging zitten.",
  "you had this one in {month} too": "deze had je in {month} ook",
  "You had this scramble on {when} too.": "Deze scramble had je op {when} ook.",
  "You have already done it today.": "Je hebt hem vandaag al gedaan.",
  "You have got slower, and by more than chance explains. It happens: too little sleep, a different cube, or too many new things at once.": "Je bent trager geworden, en meer dan toeval kan verklaren. Dat gebeurt: te weinig geslapen, andere kubus, of te veel nieuwe dingen tegelijk.",
  "You leave behind": "Je laat liggen",
  "You see nothing until you have done that many. No solve spoiled by the one before it.": "Je ziet niets tot je er zoveel gedaan hebt. Geen enkele solve verpest door de vorige.",
  "You slowed towards the end. That is getting tired, not getting worse — tomorrow you are back.": "Je liep tegen het eind trager. Dat is moe worden, niet slechter worden — morgen sta je er weer.",
  "Your aim": "Je doel",
  "Your average": "Je gemiddelde",
  "Your best days are as good as they were. That is not nothing — holding a peak is harder than reaching one.": "Je beste dagen zijn even goed als ze waren. Dat is niet niets — een piek vasthouden is moeilijker dan hem halen.",
  "Your best five are {gap} faster than your best five back then. That is you against you, and you are winning.": "Je beste vijf zijn {gap} sneller dan je beste vijf van toen. Dat is jij tegen jou, en jij wint.",
  "Your best five back then were {gap} faster. Something was there that day that is not there now.": "Je beste vijf van toen waren {gap} sneller. Die dag zat er iets in dat er nu niet in zit.",
  "Your best five in a row": "Je beste vijf op rij",
  "Your best runs": "Je beste pogingen",
  "Your colour": "Jouw kleur",
  "Your cubes": "Je kubussen",
  "Your fastest three": "Je snelste drie",
  "Your first solve under {n} seconds.": "Je eerste solve onder de {n} seconden.",
  "Your last eight are {gap} slower than your first eight. Five minutes off?": "Je laatste acht zijn {gap} trager dan je eerste acht. Even vijf minuten?",
  "Your name on the card (may be empty)": "Je naam op het kaartje (mag leeg)",
  "Your own way, e.g. R U R' U' R' F R F'": "Je eigen manier, bv. R U R' U' R' F R F'",
  "Your practice history": "Je oefengeschiedenis",
  "Your record has stood {n} day.": "Je record staat {n} dag.",
  "Your record has stood {n} days.": "Je record staat {n} dagen.",
  "Your record is from today.": "Je record is van vandaag.",
  "Your record went. {time} is on the wall from now on.": "Je record ging eraan. {time} staat vanaf nu op de muur.",
  "Your scrambles": "Je scrambles",
  "Your scrambles were": "Je scrambles waren",
  "Your scrambles were easier than usual on average. On scrambles of ordinary weight this would have been {n}s slower.": "Je scrambles waren gemiddeld makkelijker dan gewoon. Op scrambles van normale zwaarte was dit {n}s trager geweest.",
  "Your scrambles were heavier than usual. On scrambles of ordinary weight this would have been {n}s faster — your average does not flatter you.": "Je scrambles waren zwaarder dan gewoon. Op scrambles van normale zwaarte was dit {n}s sneller geweest — je gemiddelde vleit je niet.",
  "your slowest solve": "je traagste solve",
  "Your solve is evenly spread over {n} measured solves. No part stands out.": "Je solve is netjes verdeeld over {n} gemeten solves. Er springt geen enkel deel uit.",
  "Your timer": "Je timer",
  "Your timer has a time that is not here yet. Add it to \"{name}\"?": "Op je timer staat een tijd die hier nog niet bij staat. Wil je hem erbij zetten in \"{name}\"?",
  "Your timer has {n} times that are not here yet. Add them to \"{name}\"?": "Op je timer staan {n} tijden die hier nog niet bij staan. Wil je ze erbij zetten in \"{name}\"?",
  "Your timer reports {slots} slots; one of them was a duplicate or already here.": "Je timer geeft {slots} plekken door; één daarvan was dubbel of stond er al bij.",
  "Your timer reports {slots} slots; {n} of them were duplicates or already here.": "Je timer geeft {slots} plekken door; {n} daarvan waren dubbel of stonden er al bij.",
  "Your usual day is {n}.": "Je gewone dag is er {n}.",
  "Your very first time in the app.": "Je allereerste tijd in de app.",
  "Your way": "Jouw manier",
  "Your weakest third": "Je zwakste derde",
  "your weakest third": "je zwakste derde",
  "your {n} slowest solves": "je {n} traagste solves",
  "{a} of {b}": "{a} van {b}",
  "{a} {sessionWord}, {b} {timeWord}.": "{a} {sessionWord}, {b} {timeWord}.",
  "{clock} left — {n} {word}": "Nog {clock} — {n} {word}",
  "{date} at {time}": "{date} om {time}",
  "{filled} of the nine, and {rows} line full.": "{filled} van de negen, en {rows} rij vol.",
  "{filled} of the nine, and {rows} lines full.": "{filled} van de negen, en {rows} rijen vol.",
  "{gap} faster than when you started": "{gap} sneller dan toen je begon",
  "{had} of {all} steps. Up now: {name}. About {hours} hours of practice to go.": "{had} van {all} stappen. Nu aan de beurt: {name}. Nog ongeveer {hours} uur oefenen te gaan.",
  "{had} of {n}": "{had} van {n}",
  "{h} h and {m} min": "{h} uur en {m} min",
  "{id} — turn the setup, then solve the case.": "{id} — draai de opzet en solve dan het geval.",
  "{key} for inspection · hold and let go to start": "{key} voor inspectie · vasthouden en loslaten om te starten",
  "{key} for inspection · hold to start": "{key} voor inspectie · vasthouden om te starten",
  "{name} and {n} more.": "{name} en nog {n} erbij.",
  "{name} deleted.": "{name} verwijderd.",
  "{name} does not offer the GAN timer’s time service.": "{name} biedt de tijd-dienst van de GAN timer niet aan.",
  "{name} is up — {a}–{b}, round {round} of {of}": "{name} is aan zet — {a}–{b}, ronde {round} van {of}",
  "{name} — {n} times": "{name} — {n} tijden",
  "{n} case is long enough ago to wobble. That one first.": "{n} geval is lang genoeg geleden om te wankelen. Die eerst.",
  "{n} cases are long enough ago to wobble. Those first, the shakiest at the front.": "{n} gevallen zijn lang genoeg geleden om te wankelen. Die eerst, de wankelste vooraan.",
  "{n} cases, chosen by you.": "{n} gevallen, door jou gekozen.",
  "{n} chosen": "{n} gekozen",
  "{n} daily scrambles": "{n} dagscrambles",
  "{n} day overdue": "{n} dag over tijd",
  "{n} days": "{n} dagen",
  "{n} days in a row": "{n} dagen op rij",
  "{n} days overdue": "{n} dagen over tijd",
  "{n} done": "{n} gedaan",
  "{n} hour": "{n} uur",
  "{n} hours": "{n} uur",
  "{n} in a row": "{n} op rij",
  "{n} in a row under your threshold.": "{n} achter elkaar onder je drempel.",
  "{n} in a row under {time}": "{n} op rij onder {time}",
  "{n} managed": "{n} gehaald",
  "{n} minute": "{n} minuut",
  "{n} minutes": "{n} minuten",
  "{n} moves": "{n} zetten",
  "{n} moves of cross": "{n} zetten kruis",
  "{n} moves per solve": "{n} zetten per solve",
  "{n} of the nine. A new card every Monday.": "{n} van de negen. Elke maandag een nieuwe kaart.",
  "{n} puzzles": "{n} puzzels",
  "{n} solve": "{n} solve",
  "{n} solves": "{n} solves",
  "{n} solves altogether.": "{n} solves bij elkaar.",
  "{n} solves to go. Under a hundred, any difference between then and now is just as likely chance, and the app would rather not say.": "Nog {n} solves te gaan. Onder de honderd is elk verschil tussen toen en nu even goed toeval, en dan zegt de app het liever niet.",
  "{n} solves · tap one for its scramble.": "{n} solves · tik er een aan voor de scramble.",
  "{n} solves, neatly at your own pace. That is how it is built.": "{n} solves, netjes op je eigen tempo. Zo bouw je het op.",
  "{n} time": "{n} tijd",
  "{n} time added.": "{n} tijd toegevoegd.",
  "{n} time recognised": "{n} tijd herkend",
  "{n} time · {title}": "{n} tijd · {title}",
  "{n} times added.": "{n} tijden toegevoegd.",
  "{n} times back to plain.": "{n} tijden weer gewoon.",
  "{n} times copied {label}.": "{n} tijden gekopieerd {label}.",
  "{n} times deleted.": "{n} tijden verwijderd.",
  "{n} times recognised": "{n} tijden herkend",
  "{n} times saved as {name}.": "{n} tijden bewaard als {name}.",
  "{n} times · {title}": "{n} tijden · {title}",
  "{n} {word} in a row": "{n} {word} op rij",
  "{n} {word}, ": "{n} {word}, ",
  "{n}% of the time": "{n}% van de keren",
  "{penalty} on {n} times.": "{penalty} op {n} tijden.",
  "{right} of {asked} right · {time} each": "{right} van {asked} goed · {time} per keer",
  "{right}/{all} right": "{right}/{all} goed",
  "{taste} — none found in twelve tries, this is an ordinary one": "{taste} — geen gevonden in twaalf pogingen, dit is een gewone",
  "{times} times · {sessions} sessions in all": "{times} tijden · {sessions} sessies in totaal",
  "{time} added.": "{time} toegevoegd.",
  "{time} deleted.": "{time} gewist.",
  "{time} for today — {n} {word} in a row.": "{time} voor vandaag — {n} {word} op rij.",
  "{time} is back.": "{time} staat er weer.",
  "{time} of turning": "{time} aan het draaien",
  "{time} — not under {target} yet. Try {n}.": "{time} — nog niet onder {target}. Poging {n}.",
  "{time} — under {target} after {n} tries.": "{time} — onder {target} na {n} pogingen.",
  "{time} — under {target} after {n} try.": "{time} — onder {target} na {n} poging.",
  "{what} from {name}. ": "{what} uit {name}. ",
  "{what} is safe, whatever this one becomes": "{what} is binnen, wat deze ook wordt",
  "{what} moved to {name}.": "{what} verplaatst naar {name}.",
  "{what} takes {n}% more of your solve than usual. That is where your next second is, and nowhere else.": "{what} neemt {n}% meer van je solve dan gebruikelijk. Daar ligt je volgende seconde, en nergens anders.",
  "{what}: this one may be {time} at most": "{what}: deze mag max {time}",
  "★ Save": "★ Bewaren",
};
